//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontrolnayaWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Table
    {
        public int id { get; set; }
        public int idOrder { get; set; }
        public int idAnalys { get; set; }
        public int idService { get; set; }
    
        public virtual AnalyzesTable AnalyzesTable { get; set; }
        public virtual OrdersTable OrdersTable { get; set; }
        public virtual ServicesTable ServicesTable { get; set; }
    }
}
