//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontrolnayaWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Maslov_BaklanovEntities : DbContext
    {
        public Maslov_BaklanovEntities()
            : base("name=Maslov_BaklanovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalyzesTable> AnalyzesTable { get; set; }
        public virtual DbSet<Main_Table> Main_Table { get; set; }
        public virtual DbSet<OrdersTable> OrdersTable { get; set; }
        public virtual DbSet<ServicesTable> ServicesTable { get; set; }
    }
}
