//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontrolnayaWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersTable()
        {
            this.Main_Table = new HashSet<Main_Table>();
        }
    
        public int id { get; set; }
        public string OrderName { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string PatientName { get; set; }
        public string DoctorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Main_Table> Main_Table { get; set; }
    }
}
